### ISSUE TITLE
How to make Validation text appear as a tooltip?

### ISSUE THREAD

**Issue by aswinminebrat** [third774/ng-bootstrap-form-validation#11]
hello there, 
firstly ,A big thank you for your time and effort on this module this is by far the easiest the best validation module aroud !
So i'm pretty much new to Angular.
So how can i style or make this validation text appear as a tool tip ?
It would be really helpful if you can elaborate or share a snippet.
btw  i use ngx-bootstrap !!

**Comment by third774** [comment]
Unfortunately this is not supported at the moment.

Keep an eye out for an upcoming update that will add an error message component that you can place wherever you'd like.
