### ISSUE TITLE
Angular 5 - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by nat2tk** [third774/ng-bootstrap-form-validation#14]
After import  NgBootstrapFormValidationModule.forRoot() into app.module
that compile error and show message below

>  ./node_modules/ng-bootstrap-form-validation/node_modules/@angular/core/@angular/core.es5.js
> 5659:15-36 Critical dependency: the request of a dependency is an expression
> @ ./node_modules/ng-bootstrap-form-validation/node_modules/@angular/core/@angular/core.es5.js
>  @ ./node_modules/ng-bootstrap-form-validation/ng-bootstrap-form-validation/ng-bootstrap-form-validation.es5.js
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

Does anyone have any solution?

Environment
- Angular CLI: 1.5
- Angular: 5.0.3
- Webpack: 3.8.1

**Comment by yanhackcode15** [comment]
I got the same error. Running angular 5 also

**Comment by third774** [comment]
Currently working on adding Angular 5 support.

**Comment by third774** [comment]
Just published a release that should fix Angular 5 support.

**Comment by vvolodin** [comment]
Happens to me with 1.0.11:

```
WARNING in ./node_modules/ng-bootstrap-form-validation/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ng-bootstrap-form-validation/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng-bootstrap-form-validation/ng-bootstrap-form-validation/ng-bootstrap-form-validation.es5.js
 @ ./app/ngtoc/app/app.module.ts
 @ ./app/ngtoc/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app/ngtoc/main.ts
```

**Comment by third774** [comment]
@vvolodin - which version of angular are you using?
