### ISSUE TITLE
StaticInjectorError with v2.0.0 and Angular 5

### ISSUE THREAD

**Issue by kingcody** [third774/ng-bootstrap-form-validation#19]
Error:
```
Error: Uncaught (in promise): Error: StaticInjectorError[ElementRef]: 
  StaticInjectorError[ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```

Unfortunately, this is affected by dherges/ng-packagr#302, which is a child issue of dherges/ng-packagr#335. For anyone encountering these type errors, you may want to subscribe to the above mentioned issues.

**Comment by third774** [comment]
Looks like this issue has to do with the `--preserve-symlinks` flag not being present when it should be. https://github.com/dherges/ng-packagr/issues/302#issuecomment-360580550

Can we go ahead and close this?

**Comment by kingcody** [comment]
Indeed

**Comment by kingcody** [comment]
Actually @third774 I'm still having this error with prod/AOT builds. The `--preserve-symlinks` flag does not help this issue.

I believe that I have found the problem. I'm using lazy loaded routes and to have this module work in its current form, I needed to declare the `forRoot` import at the child level. However, providers should not be imported into lazy children as they have an inherited injector and the provider will not be shared with the rest of the app.

To solve this problem I needed to:
**app.module.ts**
```typescript
@NgModule({
  imports: [
    ...
    NgBootstrapFormValidationModule.forRoot(),
    ...
  ]
})
export class AppModule { }
```

**lazychild.module.ts**
```typescript
@NgModule({
  imports: [
    ...
    NgBootstrapFormValidationModule,
    ...
  ]
})
export class LazychildModule { }
```

For this to work correctly though, `NgBootstrapFormValidationModule` should not declare a `providers` array; as these would be created as duplicate copies in the child modules injector. See a2ce9e5b047bbc1eda99f03307b8b320db8b22dd

The issue will be that this change will break our current implementation directions for non-lazy child apps. It would need to be:
```typescript
@NgModule({
  imports: [
    ...
    NgBootstrapFormValidationModule.forRoot(),
    NgBootstrapFormValidationModule,
    ...
  ]
})
export class AppModule { }
```

What are your thoughts on this?

**Comment by kingcody** [comment]
Basically, we would need to follow this pattern: https://ng-bootstrap.github.io/#/getting-started

**Comment by third774** [comment]
I'm cool with that. We'll just want to make sure to bump the major version and document the change well enough that people can find the info.

Sounds like this is in line with the approach we're discussing on PR https://github.com/third774/ng-bootstrap-form-validation/pull/16, right?

**Comment by kingcody** [comment]
It is. I'd like to leave this issue open for right now, and commit a fix against it.

Perhaps we should start a `3.0.0` milestone and add the issues/ideas we want to get in there; such as this (#19), #16, update to `ng-packagr@2.0.0-rc.12`(?), and any other low hanging fruit you can think of.
