### ISSUE TITLE
Displaying error messages from server

### ISSUE THREAD

**Issue by chrisworrell** [third774/ng-bootstrap-form-validation#23]
I am trying to figure out how to display error messages from the server.  For example if I try to save something and I get a response that the name is a duplicate (or any other server side validation failed)

Basically when the submit ajax is fired if I get a 422 i then want to loop through the returned errors and then set the appropriate control to an error and then display the message.

Something along the lines of below.  It sets the control red and does all that, but I dont know how to get the message to display under the control (err[field] is the message).  I have the errors returning as {field: message}
```
err => {
                    for ( const field in err) {
                        this.form.controls[field].setErrors({"error": err[field]});
                    }
                    
                }
```

**Comment by third774** [comment]
@chrisworrell - Can you please post a more complete example of your implementation?

Have you created async validators?

https://angular.io/guide/form-validation#validator-functions

**Comment by chrisworrell** [comment]
I am looking into async validators but basically I have the following component code

`private buildForm() {
        this.regionEditForm = new FormGroup({
            'id': new FormControl(null, Validators.required),
            'name': new FormControl(null, [Validators.required, Validators.minLength(3)])
        });
    }

    private getRegion(id: number) {
        this.regionHttp.get(id).subscribe(
            (region: Region) => {
                this.regionEditForm.patchValue({ 'name': region.name });
                this.regionEditForm.patchValue({ 'id': region.id });
                this.regionEditForm.markAsPristine();
            }
        );
    }

    private onSubmit(): void {
        if (this.regionEditForm.valid) {
            this.regionHttp.update(this.regionEditForm.value).subscribe(
                () => {
                    this.toast.showSuccess('Region Updated');
                    this.activeModal.close(true);
                },
                err => {
                    for ( const field in err) {
                        this.regionEditForm.controls[field].setErrors({'name': err[field]});
                    }
                    
                }
            );
        }
    }`

When the error comes back from the server that there is a duplicate name.  I don't have this as a angular model validator so I was hoping to just be able to pull the error in and then set the form control to error and put the message from the server in the error message on the form (hopefully that means I can easily display any error message I want from the server without having to do anything on the angular side)

I am trying to take the following return from my API and display the error messages on the form

`    "message": "Validation Failed",
    "errors": [
        {
            "field": "name",
            "message": "Region with that name already exists"
        }
    ]
}`

I am looking into the async validators now though (unless you know of a way to accomplish what i mentioned without them)

Much appreciated

**Comment by chrisworrell** [comment]
I figured out how to do it with the custom messages and async validators, though I am still curious if there is a way to just simply mark a field as invalid and put a custom message in without have to build custom messages and async validators for every situation.

Thanks

**Comment by chrisworrell** [comment]
I figured out how, i just needed to use the CustomError messages area and name things properly

**Comment by third774** [comment]
Glad to hear it! 😀
