### ISSUE TITLE
Asyn Validation

### ISSUE THREAD

**Issue by ONbik-srebollo** [third774/ng-bootstrap-form-validation#24]
Hi.

All worked fine, but I need an async validation on a field. When I put it, I get an error:

```
ERROR TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ng-bootstrap-form-validation.es5.js:195
    at Array.forEach (<anonymous>)
    at FormGroupComponent.get [as messages] (ng-bootstrap-form-validation.es5.js:194)
    at Object.eval [as updateDirectives] (FormGroupComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13067)
    at checkAndUpdateView (core.es5.js:12251)
    at callViewAction (core.es5.js:12599)
    at execComponentViewsAction (core.es5.js:12531)
    at checkAndUpdateView (core.es5.js:12257)
```

The line 195 is inside this method:

```    
Object.defineProperty(FormGroupComponent.prototype, "messages", {
        /**
         * @return {?}
         */
        get: function () {
            var _this = this;
            var /** @type {?} */ messages = [];
            if (!this.isDirtyAndTouched || this.validationDisabled)
                return messages;
            this.FormControlNames.filter(function (c) { return !c.valid; }).forEach(function (control) {
                Object.keys(control.errors).forEach(function (key) { // <---- line 195
                    var /** @type {?} */ error = _this.errorMessages.find(function (error) { return error.error === key; });
                    if (!error)
                        return;
                    messages.push(error.format(_this.label, control.errors[key]));
                });
            });
            return messages;
        },
        enumerable: true,
        configurable: true
    });
```

I don't know what happens exactly. I think that the event is thrown when sync validations are done, but as field is marked as not valid but there is no errors (the field has erros = null), that line does not check if t's null and breaks.

I'm trying to validate on other ways, but i'm frustrating by the needed logic. Can you help me please? Any working example to manage the async validation on a field with reactive forms?

Thanks in advance.
Sergio

**Comment by third774** [comment]
Are you using an [async validator](https://angular.io/guide/form-validation#validator-functions)?

**Comment by ONbik-srebollo** [comment]
Yes, obviously. If I remove this validator, all works. But this validation breaks form validation.

**Comment by kingcody** [comment]
@ONbik-srebollo could you post a link to a code base or plunkr that reproduces your issue?

**Comment by ONbik-srebollo** [comment]
This is the field definition on FormGroup (with another fields):

```
    this.formGroup = this.formBuilder.group({
      'tin': [null, Validators.compose([Validators.required, tinValidator()]), this.asyncTinValidator.bind(this)],
    });
```
And this my asyn validator.

```
  asyncTinValidator(tinCtrl: FormControl): { [key: string]: any } {
    return new Promise (resolve => {
      return this.companyManager.checkTin(tinCtrl.value)
        .then(result => {
          return null;
        }).catch(error => {
          return { 'tin': { value: tinCtrl.value, message: error.error } };
        });
    });
  }
```
I would like to get a working example with this vendor, because I think this works (I've copied an example from official doc of Angular) but perhaps there is something wrong.

Thanks in advance for your patience.

**Comment by kingcody** [comment]
@ONbik-srebollo @third774 we need to filter out any `control.errors` that are `null` instead of `ValidationErrors`:

`src/lib/Components/form-group-component/form-group-component.ts#87`
```diff
- this.FormControlNames.filter(c => !c.valid)
+ this.FormControlNames.filter(c => !c.valid && !!c.errors)
```

This is the outcome with a 2 second async validation timeout:

![async-validation](https://user-images.githubusercontent.com/2544108/35479494-e437f5a8-03c6-11e8-9256-f4019940bd39.gif)

**Comment by third774** [comment]
What do y'all think of adding `.has-warning` to the form group if an async validation is pending?

**Comment by ONbik-srebollo** [comment]
Hi @third774 .

I think it's not necessary, the validation is fast and it would be confusing to the user.

Thank you @kingcody !!!

**Comment by kingcody** [comment]
I haven't done a lot of research, but do you know how we would determine if a field is pending an async validation?

**Comment by third774** [comment]
Checking the `status` property should do it.

https://angular.io/api/forms/AbstractControl

**Comment by ONbik-srebollo** [comment]
Be careful...

Now valid property is validated, that is the same as validate status !== valid. The PENDING status would be considered as error like now. I think is better @kingcody option to check if control has errors.

**Comment by third774** [comment]
We're going to address the pending status in a separate issue.

**Comment by ONbik-srebollo** [comment]
Hi @third774 and @kingcody 

I see that this will be fixed by #26 but it seems to be available on v3.

It's possible to be available on v2.2 ? I need it.

I'm trying to use it adding it to package.json:

"ng-bootstrap-form-validation": "^2.1.0-dev.20180130230430257Z.878bd2d1a9ab7c12256a15e87a9fb32458fd56b1",

But it isn't there. And I can't use dev-master, i don't know why (sorry, i'm a bit newbie).

Can you help me, please?

Thanks in advance.

**Comment by kingcody** [comment]
@ONbik-srebollo try this:
```
npm install --save ng-bootstrap-form-validation@2.1.0-dev.20180130230430257Z.878bd2d1a9ab7c12256a15e87a9fb32458fd56b1
```
or
```
yarn add ng-bootstrap-form-validation@2.1.0-dev.20180130230430257Z.878bd2d1a9ab7c12256a15e87a9fb32458fd56b1
```

**Comment by ONbik-srebollo** [comment]
Thank you so much!!!!

I don't know what happened, but now has installed correctly. Async validation know works perfectly!!!
