### ISSUE TITLE
Error while running "ng serve" JIT

### ISSUE THREAD

**Issue by spekkie2002** [third774/ng-bootstrap-form-validation#48]
Hi Guys,

After installing the 3.0.0 RC today, i keep getting a weird compiler error. (In the browser, not in the console running ng serve).

What makes it weirder for me (as a noob), is when i run it as AOT instead of JIT. It works without any error.

```
compiler.js:1016 Uncaught Error: Can't resolve all parameters for FormControlDirective: (?, [object Object]).
    at syntaxError (compiler.js:1016)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:10917)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:10810)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:10429)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.loadDirectiveMetadata (compiler.js:10291)
    at compiler.js:23857
    at Array.forEach (<anonymous>)
    at compiler.js:23856
    at Array.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:23853)
```

FYI: I installed it thru Yarn and my ng version is:

```
Angular CLI: 6.1.5
Node: 9.2.1
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

I'm quite new to Angular, i always try to clean up my sh*t by myself... But today i can't seem to find what i did wrong. All help and comments are appreciated!

Thanks!

**Comment by third774** [comment]
Thanks for testing and creating the issue!

Can you please share what the exact dev build of the module this was with from your `package.json` file?

**Comment by third774** [comment]
And maybe also what your main app module looks like?

**Comment by kingcody** [comment]
@spekkie2002 I too ran into this error recently. I still haven't found a root cause, but will report back if I do.

**Comment by third774** [comment]
@kingcody - looks like the `| null` here is causing the issue. If I remove it, I don't get the error. Any idea how we can define that type to be nullable and still resolve correctly within the DI framework? It's already being decorated with `@Optional()`, so I'm not sure why it's not working? 🤷‍♂️

https://github.com/third774/ng-bootstrap-form-validation/blob/master/projects/ng-bootstrap-form-validation/src/lib/Directives/form-control.directive.ts#L75

**Comment by third774** [comment]
Looks like this might be related? https://github.com/angular/angular/issues/25544

**Comment by kingcody** [comment]
@third774 you're correct, I'm actually in the process of testing around that in my local. Technically, by default `null` and `undefined` are assignable to all types in TypeScript, so I'm not sure that typing is providing anything. Do you have any insight as to why it was included with #45 ?

**Comment by third774** [comment]
Just merged this PR which should fix the issue - https://github.com/third774/ng-bootstrap-form-validation/pull/49

**Comment by third774** [comment]
@kingcody Ah, crap. I forgot that `strictNullChecks` was a compiler flag that is not on by default. Thanks.

**Comment by third774** [comment]
@spekkie2002 - can you try installing the `@next` build again and see if the is fixed? Thanks!

**Comment by spekkie2002** [comment]
@third774 That did the trick!

Awesome! Thanks a lot, i really appreciate it!
