### ISSUE TITLE
Relax FormValidationDirective selector

### ISSUE THREAD

**Issue by kingcody** [third774/ng-bootstrap-form-validation#50]
https://github.com/third774/ng-bootstrap-form-validation/blob/4bdc96eb04abb5a388b39eed32ef92fb57da74e3/projects/ng-bootstrap-form-validation/src/lib/Directives/form-validation.directive.ts#L17

@third774 Is there any particular reason, that you know of, that we should restrict this selector to `form` elements? In checking the `FormGroupDirective`, the selector there is simply `[formGroup]`.

https://angular.io/api/forms/FormGroupDirective
```ts
@Directive({
    selector: '[formGroup]',
    providers: [formDirectiveProvider],
    host: { '(submit)': 'onSubmit($event)', '(reset)': 'onReset()' },
    exportAs: 'ngForm'
})
class FormGroupDirective extends ControlContainer implements Form, OnChanges { }
```

**Comment by third774** [comment]
> Is there any particular reason, that you know of, that we should restrict this selector to form elements?
Nope. I'm fine with aligning our selector with the core Angular selector.

**Comment by third774** [comment]
Addressed in https://github.com/third774/ng-bootstrap-form-validation/pull/51
