### ISSUE TITLE
Submit reloads the page

### ISSUE THREAD

**Issue by ChristianGalvez23** [third774/ng-bootstrap-form-validation#56]
I have a form when I click the submit button the page gets reloaded. I don't understand why this is happenning.

1. I have already imported the modules like FormsModule and ReactiveFormsModule.
2. I am using [formGroup] directive and (ngSubmit).
3. I have a submit type button inside <form> tags.

**Comment by third774** [comment]
Closing this because it is an Angular question and not an issue with this module. If you believe this _is_ an issue with this module, please reproduce the issue on https://stackblitz.com/ or something similar and share a link.
