### ISSUE TITLE
Is it possible to write different error messages for the same error kind?

### ISSUE THREAD

**Issue by vgabv** [third774/ng-bootstrap-form-validation#61]
Let's say I have two form fields:

- one which will contain a phone number,

- another one which will contain a first name. 

 Using this package, how can I set  the message "the phone number must be of 10 digits" for the first field, and "the first name can only contain letters" for the second one? As far as I know, I can only set one error message per error kind..

**Comment by third774** [comment]
Yes! See [Form Control Specific Custom Errors](https://github.com/third774/ng-bootstrap-form-validation#form-control-specific-custom-errors)

**Comment by vgabv** [comment]
Perfect! Thanks for the quick answer
