### ISSUE TITLE
How to display errors while typing, and how to remove the green styling?

### ISSUE THREAD

**Issue by vgabv** [third774/ng-bootstrap-form-validation#62]
Hi, I have a few doubts:

- How to display errors while the user is typing instead of when he clicks away of the input?

- How to disable the green styling when a field has no errors?

**Comment by third774** [comment]
@vgabv - we currently rely on a field being both `touched` and `dirty` to determine whether or not to display feedback. Ideally I'd like to display debounced feedback when a user stops typing for more than something like 500ms. A PR for this would be welcome.

As for disabling the `success` styling, this is part of bootstrap and I'm of the opinion that it should not be disabled. If you'd like to open a PR to add that to the options, I'd be glad to merge it.

Alternatively, you could write some CSS to over-ride the styles when that class is present.

**Comment by vgabv** [comment]
ok - it'd be great to collaborate on this, i'll see when i'll have some free time
