### ISSUE TITLE
Async validator don't call validSubmit function

### ISSUE THREAD

**Issue by zak293** [third774/ng-bootstrap-form-validation#81]
Hi,
i have custom async validators:
`static checkUniqueEmail(service: UsersService, userId: number): AsyncValidatorFn {
    return (control: FormControl) => {
      return control.valueChanges.pipe(
        delay(500),
        debounceTime(500),
        distinctUntilChanged(),
        switchMap(value => service.checkUniqueEmail(control.value, userId)),
        map(res => {
          if (!res) {
            return null;
          } else {
            return {
              emailError: true
            };
          }
        }),
        first()
      );
    };
  }`

and i added that:
`email: this.fb.control('', [
        Validators.required,
        Validators.email
      ], [
       CustomValidators.checkUniqueEmail(this.service, null)
      ])`

After validation function validSubmit dont'call.
What is wrong ?

Thanks :)

**Comment by kingcody** [comment]
I believe your validator function is being called every time there is a change to the input and is returning a new observable every time, and with `distinctUntilChanged` I would think that there would need to be two `valueChanges` emissions before it would complete, but by that point your validator function has already been ran again returning a new observable that the form is waiting on to complete.

**Comment by kingcody** [comment]
I'm going to close this, but feel free to reopen if you have any more updates/discussion.
