### ISSUE TITLE
Error message not showing when compiling with Ivy angular 9

### ISSUE THREAD

**Issue by giriprashaad** [third774/ng-bootstrap-form-validation#95]
`<div class="form-group"><div><input class="form-control"/></div></div>`

doesnt show the error message after Angular upgrade to 9.

However `<div class="form-group"><input class="form-control"/></div>` does work.

This issue happens To be more specific, if

 "angularCompilerOptions": {
    "enableIvy": true,
  }
turning off Ivy compiler shows the error messages correctly.

**Comment by creamteam-de** [comment]
Same situation here.

In my case the problem happen when using bootstrap input group and like @giriprashaad says when Ivy is enabled. The input border is shown in red when there is an error but the message doesn't appear.
```
 <div class="form-group"
	[customErrorMessages]="errorMessages">
	<label for="controlId">label</label>
	<div class="input-group">
		<input 
                        id="controlId"
			class="form-control
			formControlName="controlName">
		<div class="input-group-append"
			<div class="input-group-text">
				<i></i>
			</div>
		</div>
		<div class="input-group-append">
			<div class="input-group-text">`
				<i ></i>
			</div>
		</div>
	</div>
</div>
```
Anohter case is using a swtich control
```
<div class="form-group">
	<label for="controlId"
		class="form-control-static">Switch text</label>
	<div>
		<span class="switch-class">
			<label>
				<input 
                                        id="controlId"
					type="checkbox"
					name=""
					formControlName="controlName" />
				<span></span>
			</label>
		</span>
	</div>
</div>
```

**Comment by giriprashaad** [comment]
The above PR fix works for me in Ivy.

**Comment by third774** [comment]
Thanks y'all!
